name: pulse
description: A high-fidelity prototype of a dating app called Pulse.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  lucide_icons: 0.257.0
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  go_router: ^17.1.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^17.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
